workflows:
  android-release:
    name: Android Release Build
    # Use mac_pro for 16GB+ RAM to avoid OOM during build
    instance_type: mac_pro
    max_build_duration: 60

    environment:
      flutter: stable
      java: 17
      groups:
        - google_play  # Add your environment variable group name here
      vars:
        # Increase Java heap for L8 desugaring which requires more memory
        JAVA_TOOL_OPTIONS: "-Xmx6g"
        # Gradle-specific JVM args (overrides gradle.properties on CI)
        GRADLE_OPTS: "-Xmx6g -Dorg.gradle.jvmargs=-Xmx6g -Dorg.gradle.parallel=false -Dorg.gradle.daemon=false"

    scripts:
      - name: Set up local.properties
        script: echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"

      - name: Set up keystore and key.properties
        script: |
          # If using Codemagic's code signing, the keystore is at CM_KEYSTORE_PATH
          # Otherwise, use the one committed in the repo

          KEYSTORE_PATH="${CM_KEYSTORE_PATH:-$CM_BUILD_DIR/android/app/release-keystore.jks}"

          echo "🔹 Using keystore at: $KEYSTORE_PATH"
          ls -la "$KEYSTORE_PATH" || echo "❌ Keystore not found at $KEYSTORE_PATH"

          # Create key.properties file (NO leading spaces - critical!)
          echo "storePassword=${CM_KEYSTORE_PASSWORD:-Djabari2019#}" > "$CM_BUILD_DIR/android/key.properties"
          echo "keyPassword=${CM_KEY_PASSWORD:-Djabari2019#}" >> "$CM_BUILD_DIR/android/key.properties"
          echo "keyAlias=${CM_KEY_ALIAS:-sokofiti}" >> "$CM_BUILD_DIR/android/key.properties"
          echo "storeFile=$KEYSTORE_PATH" >> "$CM_BUILD_DIR/android/key.properties"

          echo "🔹 key.properties created successfully"
          echo "🔹 Verifying key.properties contents:"
          cat "$CM_BUILD_DIR/android/key.properties" | sed 's/Password=.*/Password=***HIDDEN***/'

          echo "🔹 Verifying keystore file exists and is valid:"
          keytool -list -keystore "$KEYSTORE_PATH" -storepass "${CM_KEYSTORE_PASSWORD:-Djabari2019#}" -alias "${CM_KEY_ALIAS:-sokofiti}" 2>&1 | head -5 || echo "❌ Keystore verification failed!"

      - name: Get Flutter packages
        script: flutter pub get

      - name: Clean Gradle cache and free memory
        script: |
          cd android && ./gradlew clean --no-daemon
          # Kill any stale Gradle daemons to free memory
          ./gradlew --stop || true

      - name: Build Android App Bundle
        script: |
          # Build only AAB for Play Store (saves memory vs building both)
          flutter build appbundle --release \
            --dart-define=FLUTTER_BUILD_MODE=release

    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log

    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true

