workflows:
  android-release:
    name: Android Release Build
    # Using Linux instance (32GB RAM) for Android builds
    # If OOM persists, options:
    #   1. Use mac_pro (64GB macOS) - supports iOS too
    #   2. Build locally: flutter build appbundle --release
    # Note: Linux instances cannot build iOS apps
    instance_type: linux_x2
    max_build_duration: 60

    environment:
      flutter: stable
      java: 17
      # Note: For personal accounts, add environment variables in Codemagic UI
      # (App settings > Environment variables)
      # Required variables: GOOGLE_SERVICES_JSON, CM_KEYSTORE, CM_KEYSTORE_PASSWORD,
      # CM_KEY_PASSWORD, CM_KEY_ALIAS, GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
      vars:
        # Increase Java heap for R8/L8 (14GB on Linux - more available than macOS)
        JAVA_TOOL_OPTIONS: "-Xmx14g -Xms4g"
        # Gradle-specific JVM args (overrides gradle.properties on CI)
        GRADLE_OPTS: "-Xmx14g -Xms4g -Dorg.gradle.jvmargs=-Xmx14g -Dorg.gradle.parallel=false -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dkotlin.compiler.execution.strategy=in-process"

    scripts:
      - name: Set up local.properties
        script: echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"

      - name: Set up keystore and key.properties
        script: |
          # Decode base64 CM_KEYSTORE and create the keystore file
          if [ -n "$CM_KEYSTORE" ]; then
            echo "🔹 Decoding CM_KEYSTORE from base64..."
            echo "$CM_KEYSTORE" | base64 --decode > "$CM_BUILD_DIR/android/app/release-keystore.jks"
            KEYSTORE_PASSWORD="$CM_KEYSTORE_PASSWORD"
            KEY_PASSWORD="$CM_KEY_PASSWORD"
            KEY_ALIAS="$CM_KEY_ALIAS"
          else
            echo "🔹 Using release keystore from repo"
            KEYSTORE_PASSWORD="Djabari2019#"
            KEY_PASSWORD="Djabari2019#"
            KEY_ALIAS="sokofiti"
          fi

          echo "🔹 Creating key.properties..."

          # IMPORTANT: storeFile MUST BE RELATIVE (resolved from android/app/)
          echo "storePassword=$KEYSTORE_PASSWORD" > "$CM_BUILD_DIR/android/key.properties"
          echo "keyPassword=$KEY_PASSWORD" >> "$CM_BUILD_DIR/android/key.properties"
          echo "keyAlias=$KEY_ALIAS" >> "$CM_BUILD_DIR/android/key.properties"
          echo "storeFile=release-keystore.jks" >> "$CM_BUILD_DIR/android/key.properties"

          echo "🔹 Final key.properties:"
          cat "$CM_BUILD_DIR/android/key.properties" | sed 's/Password=.*/Password=***HIDDEN***/'

          echo "🔹 Verifying keystore:"
          keytool -list -keystore "$CM_BUILD_DIR/android/app/release-keystore.jks" \
            -storepass "$KEYSTORE_PASSWORD" \
            -alias "$KEY_ALIAS" | head -10

      - name: Decode google-services.json
        script: |
          if [ -n "$GOOGLE_SERVICES_JSON" ]; then
            echo "🔹 Decoding google-services.json from base64..."
            echo "$GOOGLE_SERVICES_JSON" | base64 --decode > "$CM_BUILD_DIR/android/app/google-services.json"
            echo "✅ google-services.json created"
          else
            echo "❌ GOOGLE_SERVICES_JSON environment variable not set!"
            exit 1
          fi

      - name: Get Flutter packages
        script: flutter pub get

      - name: Clean Gradle cache and free memory
        script: |
          # Kill any stale Gradle daemons first
          cd android && ./gradlew --stop || true

          # Clean build artifacts
          ./gradlew clean --no-daemon

          # Clear Gradle cache to free memory
          rm -rf ~/.gradle/caches/build-cache-* || true

          # Force garbage collection
          jps | grep -i gradle | awk '{print $1}' | xargs kill -9 2>/dev/null || true

          echo "🔹 Memory status after cleanup:"
          vm_stat | grep "Pages free" || free -h || true

      - name: Export Google Maps API Key
        script: |
          # Export MAPS_API_KEY for Gradle to use
          if [ -n "$MAPS_API_KEY" ]; then
            echo "✅ MAPS_API_KEY is set"
            export MAPS_API_KEY="$MAPS_API_KEY"
          else
            echo "⚠️ MAPS_API_KEY not set, using fallback from build.gradle"
          fi

      - name: Build Android App Bundle
        script: |
          # Final verification before build
          echo "🔹 Final key.properties check:"
          cat "$CM_BUILD_DIR/android/key.properties" | sed 's/Password=.*/Password=***HIDDEN***/'

          echo "🔹 Verifying keystore file exists:"
          ls -la "$CM_BUILD_DIR/android/app/release-keystore.jks"

          # Check available memory before build
          echo "🔹 Available memory:"
          vm_stat | grep "Pages free" || free -h || true

          # Build only AAB for Play Store
          flutter build appbundle --release \
            --dart-define=FLUTTER_BUILD_MODE=release

    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log

    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true

  ios-release:
    name: iOS Release Build
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      # Note: For personal accounts, add environment variables in Codemagic UI
      # Required variables: GOOGLE_SERVICE_INFO_PLIST, APP_STORE_CONNECT_PRIVATE_KEY,
      # APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_ISSUER_ID
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"

    scripts:
      - name: Decode GoogleService-Info.plist
        script: |
          if [ -n "$GOOGLE_SERVICE_INFO_PLIST" ]; then
            echo "🔹 Decoding GoogleService-Info.plist from base64..."
            echo "$GOOGLE_SERVICE_INFO_PLIST" | base64 --decode > "$CM_BUILD_DIR/ios/Runner/GoogleService-Info.plist"
            echo "✅ GoogleService-Info.plist created"
          else
            echo "❌ GOOGLE_SERVICE_INFO_PLIST environment variable not set!"
            exit 1
          fi

      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files $(xcodebuild -showBuildSettings | grep PRODUCT_BUNDLE_IDENTIFIER | awk '{print $3}') \
            --type IOS_APP_STORE \
            --create
          keychain add-certificates
          xcode-project use-profiles

      - name: Get Flutter packages
        script: flutter pub get

      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install

      - name: Build iOS IPA
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: false
