workflows:
  android-release:
    name: Android Release Build
    # Use mac_pro for 16GB+ RAM to avoid OOM during build
    instance_type: mac_pro
    max_build_duration: 60

    environment:
      flutter: stable
      java: 17
      groups:
        - google_play  # Add your environment variable group name here
      vars:
        # Increase Java heap for R8/L8 which requires more memory
        JAVA_TOOL_OPTIONS: "-Xmx12g"
        # Gradle-specific JVM args (overrides gradle.properties on CI)
        GRADLE_OPTS: "-Xmx12g -Dorg.gradle.jvmargs=-Xmx12g -Dorg.gradle.parallel=false -Dorg.gradle.daemon=false"

    scripts:
      - name: Set up local.properties
        script: echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"

      - name: Set up keystore and key.properties
        script: |
          # Decode base64 CM_KEYSTORE and create the keystore file
          if [ -n "$CM_KEYSTORE" ]; then
            echo "🔹 Decoding CM_KEYSTORE from base64..."
            echo "$CM_KEYSTORE" | base64 --decode > "$CM_BUILD_DIR/android/app/release-keystore.jks"
            KEYSTORE_PASSWORD="$CM_KEYSTORE_PASSWORD"
            KEY_PASSWORD="$CM_KEY_PASSWORD"
            KEY_ALIAS="$CM_KEY_ALIAS"
          else
            echo "🔹 Using release keystore from repo"
            KEYSTORE_PASSWORD="Djabari2019#"
            KEY_PASSWORD="Djabari2019#"
            KEY_ALIAS="sokofiti"
          fi

          echo "🔹 Creating key.properties..."

          # IMPORTANT: storeFile MUST BE RELATIVE (resolved from android/app/)
          echo "storePassword=$KEYSTORE_PASSWORD" > "$CM_BUILD_DIR/android/key.properties"
          echo "keyPassword=$KEY_PASSWORD" >> "$CM_BUILD_DIR/android/key.properties"
          echo "keyAlias=$KEY_ALIAS" >> "$CM_BUILD_DIR/android/key.properties"
          echo "storeFile=release-keystore.jks" >> "$CM_BUILD_DIR/android/key.properties"

          echo "🔹 Final key.properties:"
          cat "$CM_BUILD_DIR/android/key.properties" | sed 's/Password=.*/Password=***HIDDEN***/'

          echo "🔹 Verifying keystore:"
          keytool -list -keystore "$CM_BUILD_DIR/android/app/release-keystore.jks" \
            -storepass "$KEYSTORE_PASSWORD" \
            -alias "$KEY_ALIAS" | head -10

      - name: Get Flutter packages
        script: flutter pub get

      - name: Clean Gradle cache and free memory
        script: |
          cd android && ./gradlew clean --no-daemon
          # Kill any stale Gradle daemons to free memory
          ./gradlew --stop || true

      - name: Build Android App Bundle
        script: |
          # Final verification before build
          echo "🔹 Final key.properties check:"
          cat "$CM_BUILD_DIR/android/key.properties" | sed 's/Password=.*/Password=***HIDDEN***/'

          echo "🔹 Verifying keystore file exists:"
          ls -la "$CM_BUILD_DIR/android/app/release-keystore.jks"

          # Build only AAB for Play Store
          flutter build appbundle --release \
            --dart-define=FLUTTER_BUILD_MODE=release

    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log

    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true

